resources:
  repositories:
    - repository: sap-automation
      type: github
      name: GISComputacenter/sap-automation
      endpoint: <MyGithubConnector>
      ref: refs/heads/main

parameters:
  - name: stages
    type: stageList
    default: []

stages:
  - ${{ parameters.stages }}
